### ISSUE TITLE
Doesn't work from Ledger

### ISSUE THREAD

**Issue by michwill** [SpankChain/spankbank#47] opened 2018-09-01 19:09 UTC
Says
```
Error: gas required exceeds allowance or always failing transaction
Make sure you have enough SPANK in your wallet
Make sure you have enough Ether to pay for the transaction fee
```
The wallet does have spank and eth, and the address is correct in javascript console.

Everything works with pure software Metamask

**Comment by alexanvl** [comment] 2018-09-01 19:40
This should be fixed now, please try again.  Thanks!

**Comment by michwill** [comment] 2018-09-01 19:43
Wow. This was quick!

**Comment by michwill** [comment] 2018-09-01 21:09
Actually, now it just shows the correct amount.
But when it comes to confirming the transaction on the device, the device doesn't work (Ledger seemingly hangs as soon as it sees the transaction and shows the confirm window).

**Comment by michwill** [comment] 2018-09-01 21:50
No, I don't. The console tells me "Ledger is unplugged, locked, or the Ethereum app is not running", and the hardware wallet hangs when asking to confirm the transaction (can't neither confirm, nor cancel).

Perhaps, I need to install the latest version of firmware (my minor subversion number is smaller than current by 1), but maybe it's something else.

**Comment by michwill** [comment] 2018-09-01 21:51
The firmware version is 1.4.1

**Comment by alexanvl** [comment] 2018-09-01 22:03
@michwill Thanks for the feedback.  We're keeping a close eye out for any similar reports or additional information.  Please update us if you find a solution.

**Comment by michwill** [comment] 2018-09-01 22:04
Tried to free memory by removing an app - the issue persists

**Comment by Blockchain-Darwin** [comment] 2018-09-01 23:04
I had the same issue, I then tried it on another computer tat had Metamask installed, and it worked properly. It could be the default web3provider being used? note: I didn't use Metamask for the transaction, it was with the ledger, but having it installed might help your issue too

**Comment by michwill** [comment] 2018-09-01 23:07
I do have Metamask installed. When using Ledger, Metamask (or a default web3 provider) is still used to talk to Ethereum network, and Ledger is used just for signing transactions, as far as I understand

**Comment by alexanvl** [comment] 2018-09-03 03:43
The site will uses infura as the web3 provider and does not require MetaMask to use Ledger.  Please ensure your ledger is updated with:
firmware v1.4.2 mcu 1.5
ETH app v1.0.24
ETH app needs "browser" and "contract" support set to "yes"

**Comment by ameensol** [comment] 2018-09-04 08:44
Was this resolved @michwill ?

**Comment by alexanvl** [comment] 2018-09-06 19:55
Apologies, it appears I was incorrect. MetaMask is indeed required, even if only using ledger. We are working on better error messaging and a proper guide for staking with ledger

**Comment by ameensol** [comment] 2018-09-11 06:30
@alexanvl could you please provide an update and close the issue if it is indeed fixed?

**Comment by alexanvl** [comment] 2018-09-14 15:26
@michwill @ameensol We are still debugging Ledger staking issues but should have an ETA for fix today.  To clarify, it appears to be an issue with Ethereum app v1.1.4 specifically.  In the meantime, if you are able to downgrade the Ethereum app to v1.0.24 staking/viewing your stake should work without issue

**Comment by michwill** [comment] 2018-09-14 15:34
It's bit a principal issue for me, no problem. But will be happy to check once you have a fix

**Comment by alexanvl** [comment] 2018-09-14 19:42
Please follow https://github.com/LedgerHQ/ledger-app-eth/issues/36 for the latest on this issue

**Comment by abrkn** [comment] 2018-09-15 05:15
This issue is a duplicate of https://github.com/SpankChain/spankbank-web3/issues/6 . It's the website that communicates with the Ledger, not the contract.

**Comment by alexanvl** [comment] 2018-09-15 05:41
As @abrkn mentioned, the issue is being tracked on both the Ledger and spankbank-web3 repos since it is related to the device + interface.  I'm going to close this issue since it is not relevant to the contract.

**Closed by alexanvl** 2018-09-15 05:41 UTC
