### ISSUE TITLE
Claiming Booty before minting makes it permanently inaccessible.

### ISSUE THREAD

**Issue by zitatende** [SpankChain/spankbank#17] opened 2018-06-19 12:16 UTC
If someone claims their Booty before it has been minted, they are permanently locked out of it.

Also, if no one feels compelled to mint Booty for some period p (unlikely, of course), once p+2 starts, it can't be minted any more and, consequently, not be claimed either.
Whereas normally (i.e. if someone *does* mint) I can still withdraw my Booty many periods later.

**Comment by ameensol** [comment] 2018-06-20 04:20
The first point is valid and will be fixed. 

The second point describes the system working as intended. If no one calls `mintBooty` for a period, none of the stakers for that period will be able to withdraw Booty for that period. Keep in mind that the fact that this is the case makes it highly unlikely that calling `mintBooty` will never be _actually_ skipped.

If `mintBooty` is skipped, that's a pretty bad sign.

**Comment by zitatende** [comment] 2018-06-20 11:51
Thank you for your answer.

There's also a comment in the source code that says you have contemplated the no-minting scenario. So, if you decide it's behavior-as-intended, that's perfectly fine, of course.
In any case, I agree it's highly unlikely.

Let me add, though, that the second point just came to my mind because I'd fix the first issue by minting booty on demand. That way, no one would have to worry abount minting. The first one claiming their booty would pay for the minting -- which seems ok to me, and is likely going to happen anyway. And finally, this would make the minting process invisible from the outside, which, in my opinion, is a good thing, because I think stakers should just be able to claim their booty and not have to concern themselves with where the spankbank gets it from.

One might argue that this, in contrast to your approach, encourages lazyness in claiming your booty. Maybe so, but I'd much rather have my stakers being eager to withdraw their booty because it has value to them, than penalize them when they fail to mint, fail to check in, etc. -- which, in the end, might lead to feelings of hostility because they feel nagged.

Well, that's a difficult discussion (because there's always feedback loops with this kind of stuff), and you didn't ask for it, so I hope sharing these more fundamental thoughts doesn't bother you. Just my 2 spanks...


PS. Because I mentioned the check-ins: I know that, within the current design of the contract, the need for regular check-ins is also a technical necessity, but I'm fairly certain that an iteration-free contract design, that doesn't penalize stakers for periods of absence (and is otherwise true to the whitepaper), is possible. So, at the end of the day, it's not a technical matter, but a free choice of the rules of the game.

**Comment by ameensol** [comment] 2018-06-24 18:43
> PS. Because I mentioned the check-ins: I know that, within the current design of the contract, the need for regular check-ins is also a technical necessity, but I'm fairly certain that an iteration-free contract design, that doesn't penalize stakers for periods of absence (and is otherwise true to the whitepaper), is possible. So, at the end of the day, it's not a technical matter, but a free choice of the rules of the game.

Feel free to write it up and make a pull request :)

**Comment by ameensol** [comment] 2018-06-24 18:44
> Maybe so, but I'd much rather have my stakers being eager to withdraw their booty because it has value to them, than penalize them when they fail to mint, fail to check in, etc. -- which, in the end, might lead to feelings of hostility because they feel nagged.

I don't think asking stakers to check in once a month is a lot, and if they miss claiming their BOOTY once, they probably won't miss it again...

**Closed** 2018-06-26 19:42 UTC
